"""Shell integration tests using temporary startup files."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from lab_env.shell import (
    BLOCK_END,
    BLOCK_START,
    ShellIntegrationError,
    install_shell,
    integration_status,
    render_generated_shell,
    render_managed_block,
    resolve_shell_paths,
    uninstall_shell,
)


def test_generated_shell_includes_default_aliases(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")

    generated_shell = render_generated_shell(config_path)

    assert "# generated by lab-env" in generated_shell
    assert re.search(r"# generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", generated_shell)
    assert "# user config (persistent; make changes here):" in generated_shell
    assert f"#   {config_path}" in generated_shell
    assert "# this installed file is generated; do not edit it directly" in generated_shell
    assert "# direct changes here will be overwritten on the next install" in generated_shell
    assert "# regenerate with: lab shell install" in generated_shell
    config_section = (
        "# --------------------------------------------------\n"
        "# user configuration path\n"
        "# --------------------------------------------------\n"
        f"export LAB_ENV_CONFIG={config_path}"
    )
    assert config_section in generated_shell
    assert "# environment: initializes optional command-line tools" in generated_shell
    assert '"$HOME/miniforge3/etc/profile.d/conda.sh"' in generated_shell
    assert "/opt/miniconda3/etc/profile.d/conda.sh" in generated_shell
    assert "alias ..='cd ..'" in generated_shell
    assert "alias b='cd ..'" in generated_shell
    assert "alias l='ls -altr'" in generated_shell
    assert "alias la='ls -lah'" in generated_shell
    assert "alias ll='ls -lh'" in generated_shell
    assert "alias ls='ls -C -G -h'" in generated_shell
    assert "alias cp='cp -i'" in generated_shell
    assert "alias mv='mv -i'" in generated_shell
    assert "alias rm='rm -i'" in generated_shell
    assert 'local size="${1:-100M}"' in generated_shell
    assert 'find . -type f -size "+${size}" -exec du -h {} +' in generated_shell
    function_section = (
        "# --------------------------------------------------\n"
        "# functions managed by lab-env\n"
        "# --------------------------------------------------\n"
        "findbig() {"
    )
    assert function_section in generated_shell


def test_findbig_handles_paths_with_spaces(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    large_file = tmp_path / "directory with spaces" / "large file.bin"
    large_file.parent.mkdir()
    with large_file.open("wb") as stream:
        stream.seek(2 * 1024 * 1024 - 1)
        stream.write(b"\0")

    result = subprocess.run(
        ["/bin/zsh", "-c", f'source "{generated_path}"; cd "{tmp_path}"; findbig 1M'],
        check=True,
        capture_output=True,
        env={**os.environ, "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
        text=True,
    )

    assert "./directory with spaces/large file.bin" in result.stdout


def test_generated_shell_initializes_miniforge_from_home(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    with patch("lab_env.shell.environment.find_conda_init", return_value=None):
        generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    conda_script = tmp_path / "miniforge3" / "etc" / "profile.d" / "conda.sh"
    conda_script.parent.mkdir(parents=True)
    conda_script.write_text('conda() { printf "conda available\\n"; }\n', encoding="utf-8")

    result = subprocess.run(
        ["/bin/zsh", "-c", f'source "{generated_path}"; conda'],
        check=True,
        capture_output=True,
        env={**os.environ, "HOME": str(tmp_path), "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
        text=True,
    )

    assert result.stdout == "conda available\n"


def test_generated_shell_supports_disabling_conda_initialization(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n[shell]\ninitialize_conda = false\n",
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "_lab_env_conda_sh" not in generated_shell
    assert "etc/profile.d/conda.sh" not in generated_shell


def test_generated_shell_supports_disabled_defaults_and_custom_aliases(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n"
        "[shell]\n"
        'disabled_aliases = ["b", "rm"]\n\n'
        "[shell.aliases]\n"
        'll = "eza --long --header"\n'
        'project = "cd \\"$HOME/work/current project\\""\n\n'
        "[hosts]\n",
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "alias b=" not in generated_shell
    assert "alias rm=" not in generated_shell
    assert "alias ll='eza --long --header'" in generated_shell
    assert "alias project='cd \"$HOME/work/current project\"'" in generated_shell


def test_generated_shell_supports_disabling_all_defaults(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n"
        "[shell]\n"
        "default_aliases = false\n\n"
        "[shell.aliases]\n"
        'gs = "git status"\n',
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "alias ll=" not in generated_shell
    assert "alias rm=" not in generated_shell
    assert "alias gs='git status'" in generated_shell


def test_install_is_idempotent_and_preserves_existing_content(tmp_path: Path) -> None:
    config_path = tmp_path / "config" / "config.toml"
    config_path.parent.mkdir()
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    rc_path = tmp_path / "home" / ".zshrc"
    rc_path.parent.mkdir()
    rc_path.write_text("export EXISTING=value\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    first_result = install_shell(paths, config_path)
    installed_text = rc_path.read_text(encoding="utf-8")
    second_result = install_shell(paths, config_path)

    assert first_result.changed is True
    assert first_result.backup_path is not None
    assert first_result.backup_path.read_text(encoding="utf-8") == "export EXISTING=value\n"
    assert installed_text.startswith("export EXISTING=value\n")
    assert installed_text.count(BLOCK_START) == 1
    assert installed_text.count(BLOCK_END) == 1
    assert paths.generated_path.exists()
    assert integration_status(paths) == "installed"
    assert second_result.changed is False
    assert second_result.backup_path is None


def test_uninstall_removes_only_owned_content(tmp_path: Path) -> None:
    config_path = tmp_path / "config" / "config.toml"
    config_path.parent.mkdir()
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    rc_path = tmp_path / ".bashrc"
    rc_path.write_text("alias existing='echo existing'\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="bash", rc_path=rc_path)
    install_shell(paths, config_path)

    backup_path = uninstall_shell(paths)

    assert backup_path is not None
    assert rc_path.read_text(encoding="utf-8") == "alias existing='echo existing'\n"
    assert not paths.generated_path.exists()
    assert integration_status(paths) == "not installed"


def test_preview_rendering_does_not_write_files(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    rc_path = tmp_path / ".zshrc"
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    preview = render_managed_block(paths.generated_path)

    assert BLOCK_START in preview
    assert str(paths.generated_path) in preview
    assert not rc_path.exists()
    assert not paths.generated_path.exists()


def test_install_rejects_incomplete_managed_markers(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    rc_path = tmp_path / ".zshrc"
    rc_path.write_text(f"existing\n{BLOCK_START}\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    with pytest.raises(ShellIntegrationError, match="incomplete or duplicate"):
        install_shell(paths, config_path)

    assert rc_path.read_text(encoding="utf-8") == f"existing\n{BLOCK_START}\n"
