"""Shell integration tests using temporary startup files."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from lab_env.shell import (
    BLOCK_END,
    BLOCK_START,
    ShellIntegrationError,
    install_shell,
    integration_status,
    render_generated_shell,
    render_managed_block,
    resolve_shell_paths,
    uninstall_shell,
)


def _test_shell_executable() -> str:
    """Find an installed shell that can execute the generated portable script."""

    shell_executable = shutil.which("zsh", path=os.defpath) or shutil.which("bash", path=os.defpath)
    if shell_executable is None:
        pytest.skip("runtime shell test requires zsh or bash")
    return shell_executable


def _test_bash_executable() -> str:
    """Find Bash for login and interactive startup tests."""

    bash_executable = shutil.which("bash", path=os.defpath)
    if bash_executable is None:
        pytest.skip("Bash startup test requires bash")
    return bash_executable


def test_generated_shell_includes_default_aliases(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")

    generated_shell = render_generated_shell(config_path)

    assert "# generated by lab-env" in generated_shell
    assert re.search(r"# generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", generated_shell)
    assert "# user config (persistent; make changes here):" in generated_shell
    assert f"#   {config_path}" in generated_shell
    assert "# this installed file is generated; do not edit it directly" in generated_shell
    assert "# direct changes here will be overwritten on the next install" in generated_shell
    assert "# regenerate with: lab shell install" in generated_shell
    config_section = (
        "# --------------------------------------------------\n"
        "# user configuration path\n"
        "# --------------------------------------------------\n"
        f"export LAB_ENV_CONFIG={config_path}"
    )
    assert config_section in generated_shell
    assert "# environment: initializes optional command-line tools" in generated_shell
    assert '"$HOME/miniforge3/etc/profile.d/conda.sh"' in generated_shell
    assert "/opt/miniconda3/etc/profile.d/conda.sh" in generated_shell
    assert "alias ..='cd ..'" in generated_shell
    assert "alias b='cd ..'" in generated_shell
    assert "alias l='ls -altr'" in generated_shell
    assert "alias la='ls -lah'" in generated_shell
    assert "alias ll='ls -lh'" in generated_shell
    if sys.platform == "darwin":
        assert "alias ls='ls -C -G -h'" in generated_shell
    else:
        assert "alias ls='ls --color=auto -C -h'" in generated_shell
    assert "alias cp='cp -i'" in generated_shell
    assert "alias mv='mv -i'" in generated_shell
    assert "alias rm='rm -i'" in generated_shell
    assert 'local size="${1:-100M}"' in generated_shell
    assert 'find . -type f -size "+${size}" -exec du -h {} +' in generated_shell
    assert 'lay2pic() {\n    lab tecplot export "$@"\n}' in generated_shell
    function_section = (
        "# --------------------------------------------------\n"
        "# functions managed by lab-env\n"
        "# --------------------------------------------------\n"
        "findbig() {"
    )
    assert function_section in generated_shell


def test_findbig_handles_paths_with_spaces(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    large_file = tmp_path / "directory with spaces" / "large file.bin"
    large_file.parent.mkdir()
    with large_file.open("wb") as stream:
        stream.seek(2 * 1024 * 1024 - 1)
        stream.write(b"\0")

    result = subprocess.run(
        [
            _test_shell_executable(),
            "-c",
            f'source "{generated_path}"; cd "{tmp_path}"; findbig 1M',
        ],
        check=True,
        capture_output=True,
        env={**os.environ, "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
        text=True,
    )

    assert "./directory with spaces/large file.bin" in result.stdout


def test_qs_uses_slurm_or_pbs_command_available_on_path(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    scheduler_bin = tmp_path / "scheduler-bin"
    scheduler_bin.mkdir()

    for command_name in ("squeue", "qstat"):
        command_path = scheduler_bin / command_name
        command_path.write_text(
            f"#!/bin/sh\nprintf '{command_name}:%s\\n' \"$*\"\n",
            encoding="utf-8",
        )
        command_path.chmod(0o755)

    pbs_bin = tmp_path / "pbs-bin"
    pbs_bin.mkdir()
    pbs_command_path = pbs_bin / "qstat"
    pbs_command_path.write_text(
        "#!/bin/sh\nprintf 'qstat:%s\\n' \"$*\"\n",
        encoding="utf-8",
    )
    pbs_command_path.chmod(0o755)

    shell_environment = {
        **os.environ,
        "HOME": str(tmp_path),
        "PATH": str(scheduler_bin),
        "USER": "test-user",
    }
    slurm_result = subprocess.run(
        [_test_bash_executable(), "-c", f'source "{generated_path}"; qs --start'],
        check=True,
        capture_output=True,
        env=shell_environment,
        text=True,
    )
    pbs_environment = {**shell_environment, "PATH": str(pbs_bin)}
    pbs_result = subprocess.run(
        [_test_bash_executable(), "-c", f'source "{generated_path}"; qs --start'],
        check=True,
        capture_output=True,
        env=pbs_environment,
        text=True,
    )

    assert slurm_result.stdout.strip() == "squeue:-u test-user --start"
    assert pbs_result.stdout.strip() == "qstat:-u test-user --start"


def test_lay2pic_delegates_to_lab_tecplot_export(tmp_path: Path) -> None:
    """The legacy shortcut must delegate all behavior to the Python command."""

    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    command_bin = tmp_path / "bin"
    command_bin.mkdir()
    lab_path = command_bin / "lab"
    lab_path.write_text('#!/bin/sh\nprintf "%s\\n" "$@"\n', encoding="utf-8")
    lab_path.chmod(0o755)

    result = subprocess.run(
        [
            _test_shell_executable(),
            "-c",
            f'source "{generated_path}"; lay2pic figure.lay --width 1200',
        ],
        check=True,
        capture_output=True,
        env={**os.environ, "PATH": f"{command_bin}:/usr/bin:/bin"},
        text=True,
    )

    assert result.stdout.splitlines() == [
        "tecplot",
        "export",
        "figure.lay",
        "--width",
        "1200",
    ]


def test_generated_shell_initializes_miniforge_from_home(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    generated_path = tmp_path / "generated.sh"
    with patch("lab_env.shell.environment.find_conda_init", return_value=None):
        generated_path.write_text(render_generated_shell(config_path), encoding="utf-8")
    conda_script = tmp_path / "miniforge3" / "etc" / "profile.d" / "conda.sh"
    conda_script.parent.mkdir(parents=True)
    conda_script.write_text('conda() { printf "conda available\\n"; }\n', encoding="utf-8")

    result = subprocess.run(
        [_test_shell_executable(), "-c", f'source "{generated_path}"; conda'],
        check=True,
        capture_output=True,
        env={**os.environ, "HOME": str(tmp_path), "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
        text=True,
    )

    assert result.stdout == "conda available\n"


def test_generated_shell_supports_disabling_conda_initialization(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n[shell]\ninitialize_conda = false\n",
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "_lab_env_conda_sh" not in generated_shell
    assert "etc/profile.d/conda.sh" not in generated_shell


def test_generated_shell_supports_disabled_defaults_and_custom_aliases(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n"
        "[shell]\n"
        'disabled_aliases = ["b", "rm"]\n\n'
        "[shell.aliases]\n"
        'll = "eza --long --header"\n'
        'project = "cd \\"$HOME/work/current project\\""\n\n'
        "[hosts]\n",
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "alias b=" not in generated_shell
    assert "alias rm=" not in generated_shell
    assert "alias ll='eza --long --header'" in generated_shell
    assert "alias project='cd \"$HOME/work/current project\"'" in generated_shell


def test_generated_shell_supports_disabling_all_defaults(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text(
        "schema_version = 1\n\n"
        "[shell]\n"
        "default_aliases = false\n\n"
        "[shell.aliases]\n"
        'gs = "git status"\n',
        encoding="utf-8",
    )

    generated_shell = render_generated_shell(config_path)

    assert "alias ll=" not in generated_shell
    assert "alias rm=" not in generated_shell
    assert "alias gs='git status'" in generated_shell


def test_default_ls_alias_uses_platform_color_flag(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")

    with patch("lab_env.shell.aliases.sys.platform", "linux"):
        linux_shell = render_generated_shell(config_path)
    with patch("lab_env.shell.aliases.sys.platform", "darwin"):
        macos_shell = render_generated_shell(config_path)

    assert "alias ls='ls --color=auto -C -h'" in linux_shell
    assert "alias ls='ls -C -G -h'" in macos_shell


def test_install_is_idempotent_and_preserves_existing_content(tmp_path: Path) -> None:
    config_path = tmp_path / "config" / "config.toml"
    config_path.parent.mkdir()
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    rc_path = tmp_path / "home" / ".zshrc"
    rc_path.parent.mkdir()
    rc_path.write_text("export EXISTING=value\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    first_result = install_shell(paths, config_path)
    installed_text = rc_path.read_text(encoding="utf-8")
    second_result = install_shell(paths, config_path)

    assert first_result.changed is True
    assert first_result.backup_path is not None
    assert first_result.backup_path.read_text(encoding="utf-8") == "export EXISTING=value\n"
    assert installed_text.startswith("export EXISTING=value\n")
    assert installed_text.count(BLOCK_START) == 1
    assert installed_text.count(BLOCK_END) == 1
    assert paths.generated_path.exists()
    assert integration_status(paths) == "installed"
    assert second_result.changed is False
    assert second_result.backup_path is None


def test_uninstall_removes_only_owned_content(tmp_path: Path) -> None:
    config_path = tmp_path / "config" / "config.toml"
    config_path.parent.mkdir()
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    rc_path = tmp_path / ".bashrc"
    rc_path.write_text("alias existing='echo existing'\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="bash", rc_path=rc_path)
    install_shell(paths, config_path)

    backup_path = uninstall_shell(paths)

    assert backup_path is not None
    assert rc_path.read_text(encoding="utf-8") == "alias existing='echo existing'\n"
    assert not paths.generated_path.exists()
    assert integration_status(paths) == "not installed"


def test_preview_rendering_does_not_write_files(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    rc_path = tmp_path / ".zshrc"
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    preview = render_managed_block(paths.generated_path)

    assert BLOCK_START in preview
    assert str(paths.generated_path) in preview
    assert not rc_path.exists()
    assert not paths.generated_path.exists()


def test_install_rejects_incomplete_managed_markers(tmp_path: Path) -> None:
    config_path = tmp_path / "config.toml"
    rc_path = tmp_path / ".zshrc"
    rc_path.write_text(f"existing\n{BLOCK_START}\n", encoding="utf-8")
    paths = resolve_shell_paths(config_path, shell="zsh", rc_path=rc_path)

    with pytest.raises(ShellIntegrationError, match="incomplete or duplicate"):
        install_shell(paths, config_path)

    assert rc_path.read_text(encoding="utf-8") == f"existing\n{BLOCK_START}\n"


def test_bash_install_supports_login_and_nonlogin_shells(tmp_path: Path) -> None:
    home_path = tmp_path / "home"
    home_path.mkdir()
    config_path = home_path / ".config" / "lab-env" / "config.toml"
    config_path.parent.mkdir(parents=True)
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    bashrc_path = home_path / ".bashrc"
    bashrc_path.write_text("# existing interactive settings\n", encoding="utf-8")
    profile_path = home_path / ".profile"
    profile_path.write_text("# existing login settings\n", encoding="utf-8")

    with patch("lab_env.shell.paths.Path.home", return_value=home_path):
        paths = resolve_shell_paths(config_path, shell="bash")

    assert paths.rc_path == bashrc_path
    assert paths.login_rc_path == profile_path
    result = install_shell(paths, config_path)

    assert len(result.backup_paths) == 2
    assert BLOCK_START in bashrc_path.read_text(encoding="utf-8")
    profile_text = profile_path.read_text(encoding="utf-8")
    assert profile_text.startswith("# existing login settings\n")
    assert "${BASH_VERSION:-}" in profile_text
    assert str(bashrc_path) in profile_text
    assert integration_status(paths) == "installed"

    shell_environment = {
        "HOME": str(home_path),
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "SHELL": "/bin/bash",
    }
    login_result = subprocess.run(
        [_test_bash_executable(), "--login", "-c", "type -t findbig"],
        check=True,
        capture_output=True,
        env=shell_environment,
        text=True,
    )
    nonlogin_result = subprocess.run(
        [_test_bash_executable(), "--noprofile", "-i", "-c", "type -t findbig"],
        check=True,
        capture_output=True,
        env=shell_environment,
        text=True,
    )

    assert login_result.stdout.strip() == "function"
    assert nonlogin_result.stdout.strip() == "function"

    backup_paths = uninstall_shell(paths)

    assert len(backup_paths) == 2
    assert bashrc_path.read_text(encoding="utf-8") == "# existing interactive settings\n"
    assert profile_path.read_text(encoding="utf-8") == "# existing login settings\n"
    assert integration_status(paths) == "not installed"


def test_bash_install_avoids_duplicate_login_bridge(tmp_path: Path) -> None:
    home_path = tmp_path / "home"
    home_path.mkdir()
    config_path = tmp_path / "config.toml"
    config_path.write_text("schema_version = 1\n[hosts]\n", encoding="utf-8")
    profile_path = home_path / ".profile"
    profile_path.write_text(
        'if [ -f "$HOME/.bashrc" ]; then\n    . "$HOME/.bashrc"\nfi\n',
        encoding="utf-8",
    )

    with patch("lab_env.shell.paths.Path.home", return_value=home_path):
        paths = resolve_shell_paths(config_path, shell="bash")

    install_shell(paths, config_path)

    assert paths.login_rc_path == profile_path
    assert "lab-env bash login" not in profile_path.read_text(encoding="utf-8")
    assert integration_status(paths) == "installed"
