"""Render managed shell files and startup blocks."""

# --------------------------------------------------
# import necessary modules
# --------------------------------------------------
from __future__ import annotations

import shlex
from datetime import UTC, datetime
from pathlib import Path

from lab_env.config import load_config
from lab_env.shell.aliases import render_aliases
from lab_env.shell.functions import render_functions

BLOCK_START = "# >>> lab-env >>>"
BLOCK_END = "# <<< lab-env <<<"


# --------------------------------------------------
# function to render the generated shell fragment
# --------------------------------------------------
def render_generated_shell(config_path: Path) -> str:
    """Build the complete generated shell file sourced by Bash or Zsh.

    Args:
        config_path: Personal configuration used to render shell content.

    Returns:
        Generated shell source containing metadata, aliases, and functions.
    """

    # resolve and validate the source configuration
    resolved_config = config_path.expanduser().resolve()
    config = load_config(resolved_config)

    # build metadata that identifies when and from where the file was generated
    generated_at = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    quoted_config = shlex.quote(str(resolved_config))
    shell_sections = [
        "\n".join(
            [
                "# --------------------------------------------------",
                "# generated by lab-env",
                f"# generated at: {generated_at}",
                "# user config (persistent; make changes here):",
                f"#   {resolved_config}",
                "# this installed file is generated; do not edit it directly",
                "# direct changes here will be overwritten on the next install",
                "# regenerate with: lab shell install",
                "# --------------------------------------------------",
            ]
        ),
        "\n".join(
            [
                "# --------------------------------------------------",
                "# user configuration path",
                "# --------------------------------------------------",
                f"export LAB_ENV_CONFIG={quoted_config}",
            ]
        ),
    ]

    # append configured aliases and managed functions as independent sections
    aliases = render_aliases(config.shell)
    if aliases:
        shell_sections.append(aliases.rstrip())
    functions = render_functions()
    if functions:
        shell_sections.append(functions.rstrip())

    generated_shell = "\n\n".join(shell_sections) + "\n"
    return generated_shell


# --------------------------------------------------
# function to render managed block
# --------------------------------------------------
def render_managed_block(generated_path: Path) -> str:
    """Render the dotfile block that loads the generated shell fragment.

    Args:
        generated_path: Generated shell file loaded during shell startup.

    Returns:
        Marked shell source block managed by lab-env.
    """

    # quote the path so startup files remain valid when directories contain spaces
    quoted_path = shlex.quote(str(generated_path.expanduser().resolve()))
    managed_block = (
        f"{BLOCK_START}\nif [ -f {quoted_path} ]; then\n    . {quoted_path}\nfi\n{BLOCK_END}\n"
    )
    return managed_block
