"""Configuration data classes and shared schema constants."""

from __future__ import annotations

from dataclasses import dataclass, field

from lab_env.hosts.models import HostConfig

SCHEMA_VERSION = 1


class ConfigError(ValueError):
    """Raised when personal configuration cannot be loaded or validated."""


@dataclass(frozen=True, slots=True)
class ShellConfig:
    """Shell aliases generated by lab-env."""

    initialize_conda: bool = True
    conda_init_path: str | None = None
    default_aliases: bool = True
    disabled_aliases: tuple[str, ...] = ()
    aliases: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class LabConfig:
    """Validated personal lab-env configuration."""

    schema_version: int = SCHEMA_VERSION
    hosts: dict[str, HostConfig] = field(default_factory=dict)
    shell: ShellConfig = field(default_factory=ShellConfig)
